apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: gh-runner
spec:
  replicas: 0 # KEDA will manage replicas
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
        - name: runner
          image: myoung34/github-runner:latest
          env:
            - name: RUNNER_SCOPE
              value: "org" # Use "repo" for repository-level runners
            - name: ORG_NAME
              value: "vvxluster" # Or REPO_URL for repo-level
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-auth
                  key: personalAccessToken
            - name: LABELS
              value: "gh-keda-runner" # Custom label for your runners
            - name: RUNNER_WORKDIR
              value: "/tmp/runner"
            - name: EPHEMERAL
              value: "true"
            - name: DISABLE_AUTO_UPDATE
              value: "true"
            - name: RUNNER_GROUP
              value: "gh-runner-group"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1500m"
          volumeMounts:
            - name: work
              mountPath: /tmp/runner
      volumes:
        - name: work
          emptyDir: {}
