name: Helm Chart Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate-and-publish:
    name: Validate and Publish Helm Chart
    runs-on: [self-hosted, gh-keda-runner]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v4

      # Step 3: Lint the Helm chart
      - name: Lint Helm Chart
        run: helm lint gh-runner-chart

      # Step 4: Package the Helm chart
      - name: Package Helm Chart
        run: helm package gh-runner-chart

      # Step 5: Upload Helm Chart to GitHub Artifact Repository
      - name: Upload Helm Chart
        uses: actions/upload-artifact@v4.0.0
        with:
          name: helm-chart
          path: gh-runner-chart-*.tgz # Upload the packaged Helm chart
